language: c
before_install:
  - wget http://downloads.arduino.cc/arduino-1.8.13-linux64.tar.xz
  - tar xf arduino-1.8.13-linux64.tar.xz
  - sudo mv arduino-1.8.13 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
script:
  - arduino --verify --board arduino:avr:uno AtomGPS_wigler.ino
